// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7oLe0IJVsBLpFzCHNoMmBI-yBK1Wd9oQ',
    appId: '1:862450620980:web:edbe0c0e2a55a5041e0861',
    messagingSenderId: '862450620980',
    projectId: 'chat-app-f79cf',
    authDomain: 'chat-app-f79cf.firebaseapp.com',
    storageBucket: 'chat-app-f79cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmzdlYTUE9PlL8Y1neGQ5M-pfkKLojsBY',
    appId: '1:862450620980:android:761073de82edcce81e0861',
    messagingSenderId: '862450620980',
    projectId: 'chat-app-f79cf',
    storageBucket: 'chat-app-f79cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzZeG0kk3tn1o1UKIjblJYhDkPc5jj0pg',
    appId: '1:862450620980:ios:df1f1eb098af327b1e0861',
    messagingSenderId: '862450620980',
    projectId: 'chat-app-f79cf',
    storageBucket: 'chat-app-f79cf.appspot.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );
}
